version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    environment:
      MYSQL_ROOT_PASSWOR: root
      MYSQL_DATABASE: e_house
      MYSQL_USER: ehouse
      MYSQL_PASSWORD: mandarina4
    ports:
      - "3306:3306"
    networks:
      - mt-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mt-network
    links:
      - db
    command:
      - sh -c './wait-for db:3208'
networks:
  mt-network:
    driver: bridge